/* eslint-disable no-restricted-globals */

// This service worker is processed by workbox-webpack-plugin during build.
// workbox-webpack-plugin injects the precache manifest at build time,
// so all static assets will be cached and available offline.

import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';

clientsClaim();

// Precache all of the assets generated by the build.
// The manifest is injected automatically by workbox-webpack-plugin.
precacheAndRoute(self.__WB_MANIFEST);

// The default CRA navigation route handler — serves index.html for
// all navigations, enabling client-side routing to work offline.
const handler = createHandlerBoundToURL('/index.html');
registerRoute(
  ({ request, url }) =>
    request.mode === 'navigate' &&
    !url.pathname.startsWith('/_') &&
    url.pathname.indexOf('.') === -1,
  handler
);

// Optional: add runtime caching for audio files from R2 bucket
// Uncomment the lines below to enable caching of meditation audio
//
// import { registerRoute } from 'workbox-routing';
// import { CacheFirst } from 'workbox-strategies';
// import { ExpirationPlugin } from 'workbox-expiration';
//
// registerRoute(
//   ({ url }) => url.hostname === 'pub-e5092eb6363d42ce8ac557dbecc589f0.r2.dev',
//   new CacheFirst({
//     cacheName: 'r2-audio',
//     plugins: [
//       new ExpirationPlugin({
//         maxEntries: 30,
//         maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
//       }),
//     ],
//   })
// );

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});